-- [jooq ignore start]

INSERT INTO mail_template (id, subject, content_text, content_html)
VALUES ('EVENT_REGISTRATION_CONFIRMATION','${event.date}: Event-Registration for ${member.name}','You successfully registered for the following event:\n\"${event.title}\" at ${event.date} in ${event.location}\nDetails: ${event.url}\n\nRegistration date: ${registration.date}\nYour name: ${member.name}\nSource: ${registration.source}\n\nTo deregister from this event, please click on the following link:\n${registration.cancelurl}','<p>You successfully registered for the following event:</p>\n<p><strong>${event.title}</strong> at ${event.date} in ${event.location}</p>\n<p>Details: <em>${event.url}</em></p>\n<p><br></p>\n<p>Registration date: ${registration.date}</p>\n<p>Your name: ${member.name}</p>\n<p>Source: ${registration.source}</p>\n<p><br></p>\n<p>To deregister from this event, please click on the following link:</p>\n<p><em>${registration.cancelurl}</em></p>'),
       ('EVENT_REGISTRATION_LIMIT_REACHED','Reached ${percent} % of attendee limit','Event: \"${event.title}\" at ${event.date} in ${event.location}\nAttendee limit: ${attendee.limit}\nAttendee count: ${attendee.count}','<p>Event: <strong>${event.title}</strong> at ${event.date} in ${event.location}</p>\n<p>Attendee limit: ${attendee.limit}</p>\n<p>Attendee count: ${attendee.count}</p>'),
       ('MEMBER_CONFIRM_EMAIL','Confirm your email address','This is the first time you used the email address ${email} with the ${website.name}.\nPlease click on the following link to validate your email address:\n${validation.url}','<p>This is the first time you used the email address ${email} with the ${website.name}. Please click on the following link to validate your email address:</p>\n<p><em>${validation.url}</em></p>'),
       ('NEWSLETTER_SUBSCRIPTION_CONFIRMATION','Newsletter subscription activated','Thank you very much for subscribing to our newsletter.','<p>Thank you very much for subscribing to our newsletter.</p>'),
       ('NEWSLETTER_SUBSCRIPTION_VALIDATION','Validate your newsletter subscription','Please click on the following link to validate your newsletter subscription:\n${validation.url}','<p>Please click on the following link to validate your newsletter subscription:</p>\n<p><em>${validation.url}</em></p>'),
       ('SECURITY_RESET_PASSWORD','Reset your password','To reset your password, use the following one time password to login:\n\n${password}','<p>To reset your password, use the following one time password to login:</p>\n<pre>${password}\n</pre>');

-- [jooq ignore stop]
