-- [jooq ignore start]

INSERT INTO page (`id`, `parent`, `page_url`, `title`, `content`)
VALUES (1, 'Sponsors', 'benefits', 'Benefits of sponsoring', '<p>The Java User Group Switzerland was founded in 1998. It is the largest software engineering community in Switzerland. It has over 940 individual members, 130 company members and 28 sponsors. JUG Switzerland organizes between 50 and 60 events a year at its locations in Basel, Bern, Lucerne, St. Gallen, Zurich, and YouTube on a wide range of topics relating to Java.</p><p>Our work is largely made possible by the generous support of our sponsors, in return we offer our partners the opportunity to position themselves in the field of Java and Software Engineering.</p><hr><h3>Company Branding</h3><p>Our website, e-mails from JUG (event announcements, discounts, etc.), and slide intros show our sponsors before each event and support the brand awareness of the sponsor with a clearly defined target audience.</p><hr><h3>Java Community Support</h3><p>A sponsorship of the Java User Group supports the Java community and enables the numerous community events, which are highly appreciated and well regarded.</p><hr><h3>Recruiting</h3><p>The Java User Group Switzerland is actively used by the Java Community as a starting point for job searches. The presence as sponsors at the Java User Group Switzerland allows it to directly address initiative employees in the Java ecosystem.</p><hr><h3>Events</h3><p>Our sponsors have the opportunity to suggest topics and speakers for events that are of interest to them. Event proposals should be technical and will be reviewed by the board of JUG Switzerland.</p>'),
       (2, 'Sponsors', 'become-a-sponsor', 'How to become a sponsor', '<h3>How to become a sponsor?</h3><p>We are delighted that you are thinking of becoming a sponsor. Please <a href="mailto:info@jug.ch">contact us</a> and we will get back to you with a copy of our contract with our services and our conditions.</p><hr><h3>Difference between these sponsorships</h3><p>The different sponsorships provide different rights to the sponsors to promote themselves (e.g. through visibility of the logo, newsletter, etc.).<br>A silver sponsorship costs CHF 3000. There is no limit on the number of silver sponsors.<br>A gold sponsorship costs CHF 6000. There can only be max. five gold sponsors at a time.<br>The platinum sponsorship costs CHF 12000. There can only be one platinum sponsor.</p><p>Gold and platinum sponsorships are in high demand, free places will be given to silver sponsors first.</p>');

INSERT INTO redirect (`old_url`, `new_url`)
VALUES ('/sponsors.php', '/sponsors'),
       ('/sponsor_benefits.php', '/sponsors/benefits'),
       ('/become_sponsor.php', '/sponsors/become-a-sponsor');

INSERT INTO page (`id`, `parent`, `page_url`, `title`, `content`)
VALUES (3, 'Members', 'general', 'General Information', '<h3>What is the "Java User Group Switzerland" (JUG.CH)?</h3><p>A Java User Group (JUG) is a group of Java enthusiasts that meet to exchange ideas and knowledge about the Java platform. There are many hundred JUGs around the world. The jug.ch or "Java User Group Switzerland" is a JUG with the goal to promote the Java platform and related topics to its members in Switzerland. This is mainly done by organizing events and presentations on topics such as Java, Scala, OOP, software engineering, databases, middleware, project methodology or software architecture. Legally, the jug.ch is organized as a Swiss "Verein" (official legal entity; engl. organization, society).</p><hr/><h3>Membership</h3><p>You are allowed to join one event for free without membership (please indicate your guest status upon registration). However, certain events are only reserved for members.</p><p>We offer individual and company memberships. Your employer may already have a company membership.</p><hr/><h3>Slides from an event</h3><p>If the speaker agrees to share the slides, we publish a link to the slides&nbsp;<a href="/events/past"><strong>on the event page</strong></a>&nbsp;shortly after the event.</p><hr/><h3>Recordings of a talk</h3><p>If there is a recording of the talk and the speaker agrees to publish it, you can find it after editing at&nbsp;<a href="https://yt.jug.ch/" style="color: rgb(156, 5, 35);" rel="nofollow"><strong>yt.jug.ch</strong></a>.</p><hr/><h3>Feedback, suggestions, ideas</h3><p>We are glad to receive feedback and input on our work and our events. Please&nbsp;<a href="https://www.jug.ch/member-feedback.php" style="color: rgb(156, 5, 35);" rel="nofollow"><strong>let us know</strong></a>&nbsp;your ideas and wishes. As for events, we will try to invite your favorite speaker and/or organize a great event on your favorite topic. Just let us know and we will try our best.</p><hr/><h3>Participation and active contribution</h3><p>If you are interested please&nbsp;<a href="mailto:info@jug.ch" style="color: rgb(156, 5, 35);" rel="nofollow"><strong>contact us</strong></a>.</p>'),
       (4, 'Members', 'slack', 'Slack-Channel', '<p>In our <a href="https://jugch.slack.com/" target="_blank">slack channel for members</a> we would like to get into conversation with you.</p><p>Register at <a href="https://slack.jug.ch/" target="_blank">slack.jug.ch</a> and discuss with us and other members!</p>');

INSERT INTO redirect (`old_url`, `new_url`)
VALUES ('/members', '/members/general'),
       ('/members.php', '/members/general'),
       ('/joinus_slack.php', '/members/slack');

-- [jooq ignore stop]
